### PR TITLE
Fixed nonsensical link

### PR DESCRIPTION
**Pull request by davorg**

### CODE REVIEW

**Comment by adarshrajpathak** [comment]
I think this will not work
since folder structure is as

posts>post.md (we are here)
assests>images>demo-xss.png
index.md

**Comment by davorg** [comment]
Do you know the difference between relative and absolute URLs? The point of putting the `/` at the start of the URL is to make it an absolute URL. It always starts from the top level (the root) of your website.

It will work. But, of course, the nice thing about source code control is that you can try it out and (if it doesn't work) you can roll back the changes and you haven't lost anything except a little bit of time.

**Comment by adarshrajpathak** [comment]
@davorg 
but the op wanted the .md preview as well as the image working on the site:
/assets/images/demo-xss.png (will work on website but less chances for md preview)
../assets/images/demo-xss.png (works on preview)
/../assets/images/demo-xss.png (works on the github pages website)

**Comment by adarshrajpathak** [comment]
@asce-21 OP please merge the changes, so that we can analyse further

**Comment by davorg** [comment]
I'm not sure what you mean by ".md preview". But if you want to test a Jekyll site locally before pushing changes to GitHub, then you should really be using [the proper tools](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll).

I'm just saying that "/.." makes no sense at the start of a URL and if it works, then it only works by abusing undefined or broken behaviour in web servers.

**Comment by adarshrajpathak** [comment]
@davorg This works at both places hatsoff !! 
Sorry for arguments if any

**Comment by asce-21** [comment]
I have merged the requests and the image is being displayed on both repo and github pages site.
Thanks for the help. I am new to all github stuff.

**Pull request merged**
